"""Narrow transaction-aware ports exposed by INGEST-001."""
from __future__ import annotations
from pathlib import Path
from typing import Any, Callable, Protocol, TypeVar
from app.modules.intake.domain.models import AttentionTransition
T = TypeVar("T")


class IntakeSourceReader(Protocol):
    def source_projection(self, connection: Any, source_id: str) -> dict[str, object] | None: ...


class IntakeAttachmentBatch(Protocol):
    def add(self, source: Path, original_name: str, media_type: str | None, *, entity_type: str,
            entity_id: str, purpose: str, correlation_id: str, owning_workflow: bool = False) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self, original_failure: BaseException | None = None) -> None: ...


class IntakeFileOperations(Protocol):
    def attachment_batch(self, connection: Any) -> IntakeAttachmentBatch: ...


class IntakeAttentionOperations(Protocol):
    """Apply one reasoned attention transition on the caller's transaction."""
    def transition_attention(
        self,
        connection: Any,
        transition: AttentionTransition,
    ) -> dict[str, object]: ...


class IntakeTransaction(Protocol):
    """Persistence vocabulary for one retained-source transaction."""
    def file_connection(self) -> Any: ...
    def source(self, source_id: str) -> dict[str, object] | None: ...
    def revision(self, revision_id: str) -> dict[str, object] | None: ...
    def operation(self, key: str) -> dict[str, object] | None: ...
    def exact_source(self, origin: str, scope: str, kind: str, external_id: str) -> dict[str, object] | None: ...
    def exact_source_for_evidence(self, current_source_id: str, origin: str, scope: str, kind: str,
                                  external_id: str, content_fingerprint: str) -> dict[str, object] | None: ...
    def duplicate_source(self, content_fingerprint: str, source_id: str) -> str | None: ...
    def insert_source(self, values: dict[str, object]) -> None: ...
    def update_source(self, source_id: str, values: dict[str, object]) -> None: ...
    def insert_revision(self, values: dict[str, object]) -> None: ...
    def replace_revision(self, revision_id: str, values: dict[str, object]) -> None: ...
    def insert_attachment(self, values: dict[str, object]) -> None: ...
    def copy_attachments(self, from_revision_id: str, to_revision_id: str) -> None: ...
    def insert_operation(self, values: dict[str, object]) -> None: ...
    def insert_candidate(self, values: dict[str, object]) -> None: ...
    def source_projection(self, source_id: str) -> dict[str, object] | None: ...
    def detail_projection(self, source_id: str) -> dict[str, object] | None: ...
    def list_projections(self, **filters: Any) -> tuple[list[dict[str, object]], tuple[str, str] | None]: ...
    def record(self, *, entity_type: str, entity_id: str, action: str, before: dict | None,
               after: dict | None, reason: str, correlation_id: str, actor_kind: str = "local_operator",
               actor_reference: str | None = None) -> None: ...


class IntakeAdmissionPort(Protocol):
    def admit(self, command: Any) -> dict[str, object]: ...


class IntakeUnitOfWork(Protocol):
    def write(self, operation: Callable[[IntakeTransaction], T]) -> T: ...
    def read(self, operation: Callable[[IntakeTransaction], T]) -> T: ...
