"""Current MAINT-001 schema."""
from sqlalchemy import CheckConstraint, ForeignKey, Index, Integer, String, text
from sqlalchemy.orm import Mapped, mapped_column
from app.platform.sqlalchemy_models import LocalBase

class MaintenanceIssueModel(LocalBase):
    __tablename__="maintenance_issues"
    id: Mapped[str]=mapped_column(String, primary_key=True); property_id: Mapped[str]=mapped_column(ForeignKey("properties.id"), nullable=False); space_id: Mapped[str|None]=mapped_column(ForeignKey("spaces.id")); summary: Mapped[str]=mapped_column(String, nullable=False); description: Mapped[str]=mapped_column(String, nullable=False); category: Mapped[str]=mapped_column(String, nullable=False); category_detail: Mapped[str|None]=mapped_column(String); priority: Mapped[str]=mapped_column(String, nullable=False); status: Mapped[str]=mapped_column(String, nullable=False); reported_at_utc: Mapped[str]=mapped_column(String, nullable=False); reported_timezone: Mapped[str]=mapped_column(String, nullable=False); reporter_role: Mapped[str]=mapped_column(String, nullable=False); reporter_subject_kind: Mapped[str]=mapped_column(String, nullable=False); reporter_party_id: Mapped[str|None]=mapped_column(ForeignKey("parties.id")); reporter_display_name_snapshot: Mapped[str]=mapped_column(String, nullable=False); resolution_summary: Mapped[str|None]=mapped_column(String); resolved_at: Mapped[str|None]=mapped_column(String); cancellation_reason: Mapped[str|None]=mapped_column(String); cancelled_at: Mapped[str|None]=mapped_column(String); idempotency_key: Mapped[str]=mapped_column(String, unique=True, nullable=False); request_fingerprint: Mapped[str]=mapped_column(String, nullable=False); created_at: Mapped[str]=mapped_column(String, nullable=False); updated_at: Mapped[str]=mapped_column(String, nullable=False)
    __table_args__=(CheckConstraint("category IN ('plumbing','electrical','heating_cooling','appliance','structural','safety_security','pest','exterior_grounds','cleaning','other')"),CheckConstraint("priority IN ('low','normal','high','urgent')"),CheckConstraint("status IN ('open','in_progress','resolved','cancelled')"),CheckConstraint("reporter_role IN ('owner','tenant','manager','staff')"),CheckConstraint("reporter_subject_kind IN ('party','local_operator')"),CheckConstraint("(reporter_subject_kind='party' AND reporter_party_id IS NOT NULL) OR (reporter_subject_kind='local_operator' AND reporter_party_id IS NULL)"),CheckConstraint("(reporter_role IN ('manager','staff') AND reporter_subject_kind='local_operator') OR (reporter_role='tenant' AND reporter_subject_kind='party') OR reporter_role='owner'"),CheckConstraint("length(trim(reporter_display_name_snapshot)) BETWEEN 1 AND 240"),CheckConstraint("(category='other' AND category_detail IS NOT NULL) OR (category!='other' AND category_detail IS NULL)"),CheckConstraint("(status='resolved' AND resolution_summary IS NOT NULL AND resolved_at IS NOT NULL AND cancellation_reason IS NULL AND cancelled_at IS NULL) OR (status='cancelled' AND cancellation_reason IS NOT NULL AND cancelled_at IS NOT NULL AND resolution_summary IS NULL AND resolved_at IS NULL) OR (status IN ('open','in_progress') AND resolution_summary IS NULL AND resolved_at IS NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL)"),Index("maintenance_issues_status_priority_reported","status","priority","reported_at_utc"),Index("maintenance_issues_property_status","property_id","status","reported_at_utc"),Index("maintenance_issues_reporter_role_status_reported","reporter_role","status","reported_at_utc"),Index("maintenance_issues_reporter_party_reported","reporter_party_id","reported_at_utc"))
class MaintenanceAppointmentModel(LocalBase):
    __tablename__="maintenance_appointments"
    id: Mapped[str]=mapped_column(String, primary_key=True); issue_id: Mapped[str]=mapped_column(ForeignKey("maintenance_issues.id"),nullable=False); starts_at_utc: Mapped[str]=mapped_column(String,nullable=False); ends_at_utc: Mapped[str]=mapped_column(String,nullable=False); scheduled_timezone: Mapped[str]=mapped_column(String,nullable=False); purpose: Mapped[str]=mapped_column(String,nullable=False); instructions: Mapped[str|None]=mapped_column(String); status: Mapped[str]=mapped_column(String,nullable=False); completed_at: Mapped[str|None]=mapped_column(String); outcome_note: Mapped[str|None]=mapped_column(String); cancelled_at: Mapped[str|None]=mapped_column(String); cancellation_reason: Mapped[str|None]=mapped_column(String); idempotency_key: Mapped[str]=mapped_column(String,unique=True,nullable=False); request_fingerprint: Mapped[str]=mapped_column(String,nullable=False); created_at: Mapped[str]=mapped_column(String,nullable=False); updated_at: Mapped[str]=mapped_column(String,nullable=False)
    __table_args__=(CheckConstraint("ends_at_utc > starts_at_utc"),CheckConstraint("status IN ('scheduled','completed','cancelled')"),CheckConstraint("(status='scheduled' AND completed_at IS NULL AND outcome_note IS NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL) OR (status='completed' AND completed_at IS NOT NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL) OR (status='cancelled' AND completed_at IS NULL AND outcome_note IS NULL AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)"),Index("maintenance_appointments_issue_start","issue_id","starts_at_utc"))
class MaintenanceCostContextModel(LocalBase):
    __tablename__="maintenance_cost_contexts"
    id: Mapped[str]=mapped_column(String,primary_key=True); issue_id: Mapped[str]=mapped_column(ForeignKey("maintenance_issues.id"),nullable=False); context_kind: Mapped[str]=mapped_column(String,nullable=False); label: Mapped[str]=mapped_column(String,nullable=False); amount_minor: Mapped[int]=mapped_column(Integer,nullable=False); currency_code: Mapped[str]=mapped_column(String,nullable=False); observed_on: Mapped[str]=mapped_column(String,nullable=False); source_note: Mapped[str|None]=mapped_column(String); replaces_cost_context_id: Mapped[str|None]=mapped_column(ForeignKey("maintenance_cost_contexts.id"),unique=True); voided_at: Mapped[str|None]=mapped_column(String); void_reason: Mapped[str|None]=mapped_column(String); idempotency_key: Mapped[str]=mapped_column(String,unique=True,nullable=False); request_fingerprint: Mapped[str]=mapped_column(String,nullable=False); created_at: Mapped[str]=mapped_column(String,nullable=False)
    __table_args__=(CheckConstraint("context_kind IN ('operator_estimate','work_reported')"),CheckConstraint("typeof(amount_minor)='integer' AND amount_minor BETWEEN 1 AND 9999999999"),CheckConstraint("currency_code='USD'"),CheckConstraint("replaces_cost_context_id IS NULL OR replaces_cost_context_id != id"),CheckConstraint("(voided_at IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND void_reason IS NOT NULL)"),Index("maintenance_cost_contexts_issue","issue_id","context_kind","observed_on"))
class MaintenanceIssueExpenseLinkModel(LocalBase):
    __tablename__="maintenance_issue_expense_links"
    id: Mapped[str]=mapped_column(String,primary_key=True); issue_id: Mapped[str]=mapped_column(ForeignKey("maintenance_issues.id"),nullable=False); expense_id: Mapped[str]=mapped_column(ForeignKey("expenses.id"),nullable=False); idempotency_key: Mapped[str]=mapped_column(String,unique=True,nullable=False); request_fingerprint: Mapped[str]=mapped_column(String,nullable=False); created_at: Mapped[str]=mapped_column(String,nullable=False); archived_at: Mapped[str|None]=mapped_column(String); archive_reason: Mapped[str|None]=mapped_column(String)
    __table_args__=(CheckConstraint("(archived_at IS NULL AND archive_reason IS NULL) OR (archived_at IS NOT NULL AND archive_reason IS NOT NULL)"),Index("maintenance_expense_one_active","expense_id",unique=True,sqlite_where=text("archived_at IS NULL")),Index("maintenance_expense_issue","issue_id","archived_at"))
class MaintenanceFollowUpOperationModel(LocalBase):
    __tablename__="maintenance_follow_up_operations"
    idempotency_key: Mapped[str]=mapped_column(String,primary_key=True); request_fingerprint: Mapped[str]=mapped_column(String,nullable=False); issue_id: Mapped[str]=mapped_column(ForeignKey("maintenance_issues.id"),nullable=False); task_id: Mapped[str]=mapped_column(ForeignKey("tasks.id"),nullable=False); correlation_id: Mapped[str]=mapped_column(String,nullable=False); created_at: Mapped[str]=mapped_column(String,nullable=False)
