"""Application-owned maintenance transaction boundary."""

from __future__ import annotations

from collections.abc import Callable
from typing import Mapping, Protocol, TypeVar


Result = TypeVar("Result")


class MaintenanceTransaction(Protocol):
    """Owns maintenance rows while consuming neutral source-module projections."""

    def issue(self, issue_id: str) -> Mapping[str, object] | None: ...
    def appointment(self, appointment_id: str) -> Mapping[str, object] | None: ...
    def cost_context(self, context_id: str) -> Mapping[str, object] | None: ...
    def expense_link(self, link_id: str) -> Mapping[str, object] | None: ...
    def issue_by_key(self, key: str) -> Mapping[str, object] | None: ...
    def appointment_by_key(self, key: str) -> Mapping[str, object] | None: ...
    def cost_context_by_key(self, key: str) -> Mapping[str, object] | None: ...
    def expense_link_by_key(self, key: str) -> Mapping[str, object] | None: ...
    def follow_up_by_key(self, key: str) -> Mapping[str, object] | None: ...
    def insert_issue(self, values: Mapping[str, object]) -> None: ...
    def replace_issue(self, issue_id: str, values: Mapping[str, object]) -> None: ...
    def insert_appointment(self, values: Mapping[str, object]) -> None: ...
    def replace_appointment(self, appointment_id: str, values: Mapping[str, object]) -> None: ...
    def insert_cost_context(self, values: Mapping[str, object]) -> None: ...
    def replace_cost_context(self, context_id: str, values: Mapping[str, object]) -> None: ...
    def insert_expense_link(self, values: Mapping[str, object]) -> None: ...
    def replace_expense_link(self, link_id: str, values: Mapping[str, object]) -> None: ...
    def insert_follow_up_operation(self, values: Mapping[str, object]) -> None: ...
    def appointments_for_issue(self, issue_id: str) -> list[Mapping[str, object]]: ...
    def issue_context(self, property_id: str, space_id: str | None) -> Mapping[str, object] | None: ...
    def reporter_party(self, party_id: str) -> object | None: ...
    def reporter_party_states(self, party_ids: list[str]) -> Mapping[str, str]: ...
    def reporter_is_owner(self, property_id: str, party_id: str | None, on: str) -> bool: ...
    def reporter_is_tenant(self, property_id: str, space_id: str | None, party_id: str, on: str) -> bool: ...
    def expense(self, expense_id: str) -> Mapping[str, object] | None: ...
    def active_expense_link(self, expense_id: str) -> bool: ...
    def task(self, task_id: str) -> Mapping[str, object] | None: ...
    def tasks_for_issues(self, issue_ids: list[str]) -> dict[str, list[Mapping[str, object]]]: ...
    def create_task(self, command: object, *, correlation_id: str) -> object: ...
    def issues_page(self, **filters: object) -> tuple[list[Mapping[str, object]], tuple[str, str, str] | None]: ...
    def projection(self, issue_ids: list[str], *, include_detail: bool = True) -> dict[str, Mapping[str, object]]: ...
    def record_change(self, **change: object) -> None: ...


class MaintenanceUnitOfWork(Protocol):
    def write(self, operation: Callable[[MaintenanceTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[MaintenanceTransaction], Result]) -> Result: ...
