from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.owner_management.domain.models import Concern
from app.modules.tasks.domain.models import Task

Result = TypeVar("Result")


class OwnerConcernTransaction(Protocol):
    def concern(self, concern_id: str) -> Concern | None: ...
    def command_operation(self, operation_id: str) -> dict[str, object] | None: ...
    def command_operation_by_key(self, key: str) -> dict[str, object] | None: ...
    def insert_command_operation(self, values: dict[str, object]) -> None: ...
    def insert_concern(self, concern: Concern) -> None: ...
    def replace_concern(self, concern: Concern) -> None: ...
    def insert_follow_up_operation(self, values: dict[str, object]) -> None: ...
    def duplicate_candidates(self, **filters: Any) -> list[str]: ...
    def concern_page(self, **filters: Any) -> list[Concern]: ...
    def context(self, **values: Any) -> dict[str, object]: ...
    def active_property(self, property_id: str) -> None: ...
    def originating_communication(
        self, communication_id: str, owner_party_id: str, property_id: str
    ) -> bool: ...
    def create_task(self, values: dict[str, object], *, correlation_id: str) -> Task: ...
    def task_views(self, concern_ids: list[str]) -> dict[str, list[dict[str, object]]]: ...
    def active_task_counts(self, concern_ids: list[str]) -> dict[str, int]: ...
    def communication_counts(self, concern_ids: list[str]) -> dict[str, int]: ...
    def detail_projection(self, concern: Concern) -> dict[str, object]: ...
    def record_change(self, **change: Any) -> None: ...


class OwnerConcernUnitOfWork(Protocol):
    def write(self, operation: Callable[[OwnerConcernTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[OwnerConcernTransaction], Result]) -> Result: ...


class PropertyArchiveConcernGuard(Protocol):
    def conflict(self, connection: Any, property_id: str) -> str | None: ...
