from __future__ import annotations
from pathlib import Path
from typing import Protocol

class StoredContent(Protocol):
    relative_path: str
    size_bytes: int
    content_sha256: str
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

class FileContentStore(Protocol):
    def store(self, source: Path) -> StoredContent: ...
    def path_for(self, relative_path: str, content_hash: str, size: int) -> Path: ...

class FileMetadataRepository(Protocol):
    def create(self, item, entity_type: str | None, entity_id: str | None, purpose: str) -> None: ...
    def get(self, file_id: str): ...
