"""Bounded, consumer-neutral property recognition reads."""

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol
import unicodedata

from app.modules.portfolio.application.service import PortfolioError

MAX_DIRECTORY_TEXT = 240
MAX_DIRECTORY_ITEMS = 100
RECOGNITION_PREVIEW_LIMIT = 3


@dataclass(frozen=True)
class PropertyDirectoryQuery:
    text: str = ""
    status: str = "active"
    ownership_context: str | None = None
    occupancy: str | None = None
    availability: str | None = None
    needs_attention: bool | None = None
    limit: int = 50

    def __post_init__(self):
        if not isinstance(self.text, str) or len(self.text) > MAX_DIRECTORY_TEXT:
            raise PortfolioError("Property search must be at most 240 characters.")
        if (
            self.status not in {"active", "archived", "all"}
            or self.ownership_context not in {None, "self_owned", "managed_for_owner", "mixed"}
            or self.occupancy not in {None, "unknown", "occupied", "vacant"}
            or self.availability
            not in {None, "available_now", "available_on", "not_available", "unknown"}
            or (self.needs_attention is not None and type(self.needs_attention) is not bool)
            or type(self.limit) is not int
            or not 1 <= self.limit <= MAX_DIRECTORY_ITEMS
        ):
            raise PortfolioError("Property directory filters or bounds are invalid.")
        object.__setattr__(
            self, "text", unicodedata.normalize("NFKC", self.text.strip()).casefold()
        )


class PortfolioDirectoryReader(Protocol):
    def calendar_signature(self, connection: Any, as_of: datetime) -> str:
        """Distinct property-zone local dates, for effective-date invalidation."""
        ...

    def properties(
        self,
        connection: Any,
        query: PropertyDirectoryQuery,
        *,
        as_of: datetime,
        after: tuple[str, str] | None,
    ) -> tuple[int, list[Mapping[str, Any]]]:
        """Count matching records and return at most limit+1 bounded cards.

        Cards carry snake_case identity/address facts, effective ownership,
        space/owner counts, and at most three current space/owner previews.
        Sort keys are generated by the same expression used for selection.
        All reads use the supplied connection and aware instant.
        """
        ...
