"""Application ports for atomic portfolio changes."""

from __future__ import annotations

from collections.abc import Callable, Collection
from typing import Any, Protocol, TypeVar

from app.modules.portfolio.domain.models import (
    Party,
    Property,
    PropertyOwnership,
    Space,
    SpaceAvailability,
    SpaceOccupancyPeriod,
)

Result = TypeVar("Result")


class PortfolioContextReader(Protocol):
    """Transaction-aware property, space, and ownership context reads."""

    def context_for_space(self, connection: Any, space_id: str) -> dict[str, object] | None: ...
    def contexts_for_spaces(self, connection: Any, space_ids: Collection[str]) -> dict[str, dict[str, object]]: ...
    def context_for_property_space(self, connection: Any, property_id: str, space_id: str | None) -> dict[str, object] | None: ...
    def contexts_for_property_spaces(self, connection: Any, references: Collection[tuple[str, str | None]]) -> dict[tuple[str, str | None], dict[str, object]]: ...
    def party_owned_property_on(self, connection: Any, property_id: str, party_id: str, on: str) -> bool: ...
    def ownership_subject_kinds_on(self, connection: Any, property_id: str, on: str) -> set[tuple[str, str | None]]: ...


class AddressTimeZoneResolver(Protocol):
    """Resolves a structured local address without contacting an external service."""

    def resolve(
        self,
        *,
        address_line_1: str,
        city: str,
        region: str | None,
        postal_code: str | None,
        country_code: str,
    ) -> str: ...


class PartyRoleActivityGuard(Protocol):
    def conflict(self, connection: Any, party_id: str) -> str | None: ...

class PropertyArchiveGuard(Protocol):
    def conflict(self, connection: Any, property_id: str) -> str | None: ...


class PortfolioConflictError(RuntimeError):
    """The requested change conflicts with concurrent or source-owned state."""

    def __init__(self, message: str, *, current_status: dict[str, object] | None = None) -> None:
        super().__init__(message)
        self.current_status = current_status


class PortfolioTransaction(Protocol):
    def get_property(self, property_id: str) -> Property | None: ...
    def get_party(self, party_id: str) -> Party | None: ...
    def ownerships_at(self, property_id: str, when: str) -> list[PropertyOwnership]: ...
    def future_ownerships(self, property_id: str, after: str) -> list[PropertyOwnership]: ...
    def open_ownerships_for_party(self, party_id: str, today: str) -> list[PropertyOwnership]: ...
    def party_role_conflicts(self, party_id: str) -> list[str]: ...
    def property_archive_conflicts(self, property_id: str) -> list[str]: ...
    def insert_party(self, party: Party) -> None: ...
    def replace_party(self, party: Party) -> None: ...
    def insert_property(self, property: Property) -> None: ...
    def replace_property(self, property: Property) -> None: ...
    def insert_ownership(self, ownership: PropertyOwnership) -> None: ...
    def end_ownership(self, ownership: PropertyOwnership) -> None: ...
    def get_space(self, space_id: str) -> Space | None: ...
    def spaces(self, property_id: str, *, active_only: bool = False) -> list[Space]: ...
    def insert_space(self, space: Space) -> None: ...
    def replace_space(self, space: Space) -> None: ...
    def occupancy_periods(self, space_id: str) -> list[SpaceOccupancyPeriod]: ...
    def availability(self, space_id: str) -> SpaceAvailability | None: ...
    def insert_occupancy_period(self, period: SpaceOccupancyPeriod) -> None: ...
    def replace_occupancy_period(self, period: SpaceOccupancyPeriod) -> None: ...
    def insert_availability(self, availability: SpaceAvailability) -> None: ...
    def replace_availability(self, availability: SpaceAvailability) -> None: ...
    def status_operation(self, idempotency_key: str) -> dict[str, object] | None: ...
    def insert_status_operation(self, operation: dict[str, object]) -> None: ...
    def property_views(self, *, status: str | None = None) -> list[tuple[Property, list[PropertyOwnership], dict[str, Party], list[Space]]]: ...
    def property_page_ids(self, *, status: str | None, ownership_context: str | None, occupancy: str | None, availability: str | None, needs_attention: bool | None, local_days: dict[str, str], cursor: tuple[str, str] | None, limit: int) -> tuple[list[str], int]: ...
    def property_time_zones(self) -> set[str]: ...
    def property_views_for_ids(self, property_ids: list[str]) -> list[tuple[Property, list[PropertyOwnership], dict[str, Party], list[Space]]]: ...
    def space_statuses(self, space_ids: list[str]) -> tuple[dict[str, list[SpaceOccupancyPeriod]], dict[str, SpaceAvailability]]: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str,
                      before: dict[str, Any] | None, after: dict[str, Any] | None,
                      reason: str, correlation_id: str) -> None: ...


class PortfolioUnitOfWork(Protocol):
    def write(self, operation: Callable[[PortfolioTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[PortfolioTransaction], Result]) -> Result: ...
    def get_property(self, property_id: str) -> Property | None: ...
    def get_space(self, space_id: str) -> Space | None: ...
    def ownerships(self, property_id: str) -> list[PropertyOwnership]: ...
    def spaces(self, property_id: str, *, active_only: bool = False) -> list[Space]: ...
    def parties(self, *, active_only: bool = False) -> list[Party]: ...
    def parties_for_ownerships(self, ownerships: list[PropertyOwnership]) -> dict[str, Party]: ...
    def property_views(self, *, status: str | None = None) -> list[tuple[Property, list[PropertyOwnership], dict[str, Party], list[Space]]]: ...
    def space_statuses(self, space_ids: list[str]) -> tuple[dict[str, list[SpaceOccupancyPeriod]], dict[str, SpaceAvailability]]: ...
