"""Application ports for atomic portfolio changes."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.portfolio.domain.models import (
    Party,
    Property,
    PropertyOwnership,
    Space,
    SpaceAvailability,
    SpaceOccupancyPeriod,
)

Result = TypeVar("Result")


class AddressTimeZoneResolver(Protocol):
    """Resolves a structured local address without contacting an external service."""

    def resolve(
        self,
        *,
        address_line_1: str,
        city: str,
        region: str | None,
        postal_code: str | None,
        country_code: str,
    ) -> str: ...


class PartyRoleActivityGuard(Protocol):
    def conflict(self, connection: Any, party_id: str) -> str | None: ...


class PortfolioConflictError(RuntimeError):
    """The requested change conflicts with concurrent or source-owned state."""


class PortfolioTransaction(Protocol):
    def get_property(self, property_id: str) -> Property | None: ...
    def get_party(self, party_id: str) -> Party | None: ...
    def ownerships_at(self, property_id: str, when: str) -> list[PropertyOwnership]: ...
    def future_ownerships(self, property_id: str, after: str) -> list[PropertyOwnership]: ...
    def open_ownerships_for_party(self, party_id: str, today: str) -> list[PropertyOwnership]: ...
    def party_role_conflicts(self, party_id: str) -> list[str]: ...
    def insert_party(self, party: Party) -> None: ...
    def replace_party(self, party: Party) -> None: ...
    def insert_property(self, property: Property) -> None: ...
    def replace_property(self, property: Property) -> None: ...
    def insert_ownership(self, ownership: PropertyOwnership) -> None: ...
    def end_ownership(self, ownership: PropertyOwnership) -> None: ...
    def get_space(self, space_id: str) -> Space | None: ...
    def spaces(self, property_id: str, *, active_only: bool = False) -> list[Space]: ...
    def insert_space(self, space: Space) -> None: ...
    def replace_space(self, space: Space) -> None: ...
    def occupancy_periods(self, space_id: str) -> list[SpaceOccupancyPeriod]: ...
    def availability(self, space_id: str) -> SpaceAvailability | None: ...
    def insert_occupancy_period(self, period: SpaceOccupancyPeriod) -> None: ...
    def replace_occupancy_period(self, period: SpaceOccupancyPeriod) -> None: ...
    def insert_availability(self, availability: SpaceAvailability) -> None: ...
    def replace_availability(self, availability: SpaceAvailability) -> None: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str,
                      before: dict[str, Any] | None, after: dict[str, Any] | None,
                      reason: str, correlation_id: str) -> None: ...


class PortfolioUnitOfWork(Protocol):
    def write(self, operation: Callable[[PortfolioTransaction], Result]) -> Result: ...
    def get_property(self, property_id: str) -> Property | None: ...
    def get_space(self, space_id: str) -> Space | None: ...
    def ownerships(self, property_id: str) -> list[PropertyOwnership]: ...
    def spaces(self, property_id: str, *, active_only: bool = False) -> list[Space]: ...
    def parties(self, *, active_only: bool = False) -> list[Party]: ...
    def parties_for_ownerships(self, ownerships: list[PropertyOwnership]) -> dict[str, Party]: ...
    def property_views(self, *, status: str | None = None) -> list[tuple[Property, list[PropertyOwnership], dict[str, Party], list[Space]]]: ...
    def space_statuses(self, space_ids: list[str]) -> tuple[dict[str, list[SpaceOccupancyPeriod]], dict[str, SpaceAvailability]]: ...
