from collections.abc import Callable
from typing import Any, Protocol, TypeVar
from app.modules.owner_accounting.domain.models import OwnerRentReport

Result = TypeVar("Result")
class OwnerRentReportTransaction(Protocol):
    def report(self, report_id: str) -> OwnerRentReport | None: ...
    def report_by_operation_key(self, key: str) -> dict[str, object] | None: ...
    def insert_report(self, item: OwnerRentReport) -> None: ...
    def replace_report(self, item: OwnerRentReport) -> None: ...
    def insert_operation(self, item: dict[str, object]) -> None: ...
    def replacement_exists(self, report_id: str) -> bool: ...
    def replacement_for_report(self, report_id: str) -> OwnerRentReport | None: ...
    def report_for_receipt(self, receipt_id: str) -> OwnerRentReport | None: ...
    def report_page(self, **filters: Any) -> list[OwnerRentReport]: ...
    def record_change(self, **change: Any) -> None: ...
    def lease_context(self, lease_id: str) -> dict[str, object] | None: ...
    def owner_party(self, party_id: str) -> Any | None: ...
    def owner_parties(self, party_ids: list[str]) -> dict[str, Any]: ...
    def owner_eligible(self, property_id: str, party_id: str, on: str) -> bool: ...
    def has_evidence(self, report_id: str) -> bool: ...
    def evidence_count(self, report_id: str) -> int: ...
    def evidence_counts(self, report_ids: list[str]) -> dict[str, int]: ...
    def evidence_links(self, report_id: str) -> list[Any]: ...
    def available_evidence_links(self, report_id: str) -> list[Any]: ...
    def receipt(self, receipt_id: str) -> Any | None: ...
    def receipts(self, receipt_ids: list[str]) -> dict[str, Any]: ...
    def receipt_allocations(self, receipt_id: str) -> list[dict[str, Any]]: ...
    def receipt_projections(self, receipt_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def replacement_receipt(self, receipt_id: str) -> Any | None: ...
    def record_receipt(self, command: Any, *, now: Callable[[], Any], correlation_id: str, audit_reason: str, duplicate_conflict: Callable[[list[Any]], Exception] | None = None) -> Any: ...
class OwnerRentReportUnitOfWork(Protocol):
    def write(self, operation: Callable[[OwnerRentReportTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[OwnerRentReportTransaction], Result]) -> Result: ...
