"""Transaction ports for lease use cases."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.leases.domain.models import (
    Lease,
    LeaseParticipant,
    LeaseRenewalOption,
    LeaseTerm,
    LeaseTerminationCase,
    LeaseTerminationProposal,
)
from app.modules.portfolio.domain.models import Property, Space, SpaceOccupancyPeriod

Result = TypeVar("Result")


class TenantProfileAvailability(Protocol):
    def is_active(self, connection: Any, party_id: str) -> bool: ...


class PortfolioLeaseOperations(Protocol):
    """Portfolio reads and occupancy writes inside a lease-owned transaction."""

    def space(self, connection: Any, space_id: str) -> Space | None: ...
    def property(self, connection: Any, property_id: str) -> Property | None: ...
    def occupancy_periods(self, connection: Any, space_id: str) -> list[SpaceOccupancyPeriod]: ...
    def insert_occupancy_period(self, connection: Any, item: SpaceOccupancyPeriod) -> None: ...
    def replace_occupancy_period(self, connection: Any, item: SpaceOccupancyPeriod) -> None: ...
    def space_ids_for_property(self, property_id: str) -> list[str]: ...


class LeaseConflictError(RuntimeError):
    """A lease operation conflicts with stored or concurrently changed state."""


class LeaseTransaction(Protocol):
    def lease(self, lease_id: str) -> Lease | None: ...
    def space(self, space_id: str) -> Space | None: ...
    def property(self, property_id: str) -> Property | None: ...
    def tenant_profile_active(self, party_id: str) -> bool: ...
    def terms(self, lease_id: str) -> list[LeaseTerm]: ...
    def participants(self, lease_id: str) -> list[LeaseParticipant]: ...
    def renewal_options(self, lease_id: str) -> list[LeaseRenewalOption]: ...
    def termination_cases(self, lease_id: str) -> list[LeaseTerminationCase]: ...
    def termination_case(self, case_id: str) -> LeaseTerminationCase | None: ...
    def termination_proposals(self, case_id: str) -> list[LeaseTerminationProposal]: ...
    def occupancy_periods(self, space_id: str) -> list[SpaceOccupancyPeriod]: ...
    def insert_lease(self, item: Lease) -> None: ...
    def replace_lease(self, item: Lease) -> None: ...
    def insert_term(self, item: LeaseTerm) -> None: ...
    def delete_terms(self, lease_id: str) -> None: ...
    def insert_participant(self, item: LeaseParticipant) -> None: ...
    def replace_participant(self, item: LeaseParticipant) -> None: ...
    def delete_participant(self, participant_id: str) -> None: ...
    def insert_renewal_option(self, item: LeaseRenewalOption) -> None: ...
    def replace_renewal_option(self, item: LeaseRenewalOption) -> None: ...
    def insert_termination_case(self, item: LeaseTerminationCase) -> None: ...
    def replace_termination_case(self, item: LeaseTerminationCase) -> None: ...
    def insert_termination_proposal(self, item: LeaseTerminationProposal) -> None: ...
    def replace_termination_proposal(self, item: LeaseTerminationProposal) -> None: ...
    def insert_occupancy_period(self, item: SpaceOccupancyPeriod) -> None: ...
    def replace_occupancy_period(self, item: SpaceOccupancyPeriod) -> None: ...
    def record_change(
        self,
        *,
        entity_type: str,
        entity_id: str,
        action: str,
        before: dict[str, Any] | None,
        after: dict[str, Any] | None,
        reason: str,
        correlation_id: str,
    ) -> None: ...


class LeaseUnitOfWork(Protocol):
    def write(self, operation: Callable[[LeaseTransaction], Result]) -> Result: ...
    def lease_view(self, lease_id: str) -> tuple[Lease, list[LeaseTerm], list[LeaseParticipant], list[LeaseRenewalOption], list[dict[str, object]]] | None: ...
    def lease_views(
        self,
        *,
        status: str | None,
        property_id: str | None,
        space_id: str | None,
        tenant_party_id: str | None,
        contract_start_from: str | None,
        contract_start_to: str | None,
        renewal_due_on_or_before: str | None,
    ) -> list[tuple[Lease, list[LeaseTerm], list[LeaseParticipant], list[LeaseRenewalOption], list[dict[str, object]]]]: ...
    def termination_case_view(self, case_id: str) -> tuple[LeaseTerminationCase, list[LeaseTerminationProposal], list[dict[str, object]]] | None: ...
    def termination_case_views(self, lease_id: str) -> list[tuple[LeaseTerminationCase, list[LeaseTerminationProposal], list[dict[str, object]]]]: ...
    def file_link_target_exists(self, connection: Any, entity_type: str, entity_id: str) -> bool: ...
