"""Ports for transactional task persistence."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.tasks.domain.models import Task, TaskReminder

Result = TypeVar("Result")


class TaskTransaction(Protocol):
    """A single write transaction; it contains no task lifecycle policy."""

    def get_task(self, task_id: str) -> Task | None: ...
    def insert_task(self, task: Task) -> None: ...
    def replace_task(self, task: Task) -> None: ...
    def pending_reminders(self, task_id: str) -> list[TaskReminder]: ...
    def insert_reminder(self, reminder: TaskReminder) -> None: ...
    def get_reminder(self, task_id: str, reminder_id: str) -> TaskReminder | None: ...
    def replace_reminder(self, reminder: TaskReminder) -> None: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str,
                      before: dict[str, Any] | None, after: dict[str, Any] | None,
                      reason: str, correlation_id: str) -> None: ...


class TaskUnitOfWork(Protocol):
    """Executes an application-owned task change atomically."""

    def write(self, operation: Callable[[TaskTransaction], Result]) -> Result: ...
    def get(self, task_id: str) -> Task | None: ...
    def list(self, status: str | None = None) -> list[Task]: ...
    def reminders(self, task_id: str | None = None) -> list[TaskReminder]: ...
