"""Ports for transactional task persistence."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.tasks.domain.models import Task, TaskReminder

Result = TypeVar("Result")


class TaskTransactionOperations(Protocol):
    """Task persistence used inside another module's existing transaction."""

    def insert_task(self, connection: Any, task: Task) -> None: ...
    def insert_reminder(self, connection: Any, reminder: TaskReminder) -> None: ...
    def pending_reminders(self, connection: Any, task_id: str) -> list[TaskReminder]: ...
    def replace_reminder(self, connection: Any, reminder: TaskReminder) -> None: ...
    def latest_reminder_status(self, connection: Any, task_id: str) -> str | None: ...
    def create_task(self, connection: Any, command: Any, *, correlation_id: str,
                    record_change: Callable[..., None]) -> Task: ...


class TaskContextReader(Protocol):
    """Read-only task summaries for another aggregate's projection."""

    def task(self, connection: Any, task_id: str) -> dict[str, Any] | None: ...
    def tasks_for_related_entities(self, connection: Any, entity_type: str,
                                   entity_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def related_entity_ids_with_active_tasks(self, connection: Any, entity_type: str) -> set[str]: ...
    def active_related_entity_ids(self, connection: Any, entity_type: str, entity_ids: list[str]) -> set[str]: ...


class TaskTransaction(Protocol):
    """A single write transaction; it contains no task lifecycle policy."""

    def get_task(self, task_id: str) -> Task | None: ...
    def insert_task(self, task: Task) -> None: ...
    def replace_task(self, task: Task) -> None: ...
    def pending_reminders(self, task_id: str) -> list[TaskReminder]: ...
    def insert_reminder(self, reminder: TaskReminder) -> None: ...
    def get_reminder(self, task_id: str, reminder_id: str) -> TaskReminder | None: ...
    def replace_reminder(self, reminder: TaskReminder) -> None: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str,
                      before: dict[str, Any] | None, after: dict[str, Any] | None,
                      reason: str, correlation_id: str) -> None: ...


class TaskUnitOfWork(Protocol):
    """Executes an application-owned task change atomically."""

    def write(self, operation: Callable[[TaskTransaction], Result]) -> Result: ...
    def get(self, task_id: str) -> Task | None: ...
    def list(self, status: str | None = None) -> list[Task]: ...
    def page(self, *, statuses: tuple[str, ...], priorities: tuple[str, ...] | None,
             related_entity_type: str | None, related_entity_id: str | None, limit: int,
             cursor: tuple[int, str | None, str, str] | None) -> list[Task]: ...
    def reminders(self, task_id: str | None = None) -> list[TaskReminder]: ...
