"""SQLAlchemy metadata owned by FIN-001."""
from sqlalchemy import CheckConstraint, ForeignKey, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from app.platform.sqlalchemy_models import LocalBase

class RentExpectationModel(LocalBase):
    __tablename__ = "rent_expectations"
    id: Mapped[str] = mapped_column(String, primary_key=True); lease_id: Mapped[str] = mapped_column(ForeignKey("leases.id"), nullable=False); lease_term_id: Mapped[str] = mapped_column(ForeignKey("lease_term_versions.id"), nullable=False); period_starts_on: Mapped[str] = mapped_column(String, nullable=False); period_ends_on: Mapped[str] = mapped_column(String, nullable=False); due_on: Mapped[str] = mapped_column(String, nullable=False); expected_amount_minor: Mapped[int] = mapped_column(Integer, nullable=False); currency_code: Mapped[str] = mapped_column(String, nullable=False); payment_frequency: Mapped[str] = mapped_column(String, nullable=False); schedule_anchor_on: Mapped[str] = mapped_column(String, nullable=False); is_prorated: Mapped[bool] = mapped_column(Integer, nullable=False); proration_numerator_days: Mapped[int | None] = mapped_column(Integer); proration_denominator_days: Mapped[int | None] = mapped_column(Integer); responsibility_boundary_on: Mapped[str | None] = mapped_column(String); responsibility_override_reason: Mapped[str | None] = mapped_column(String); voided_at: Mapped[str | None] = mapped_column(String); void_reason: Mapped[str | None] = mapped_column(String); created_at: Mapped[str] = mapped_column(String, nullable=False)
    __table_args__ = (CheckConstraint("typeof(expected_amount_minor) = 'integer' AND expected_amount_minor > 0"), CheckConstraint("currency_code = 'USD'"), CheckConstraint("payment_frequency IN ('monthly', 'weekly')"), CheckConstraint("period_ends_on > period_starts_on AND due_on >= period_starts_on AND due_on <= period_ends_on"), CheckConstraint("is_prorated IN (0, 1)"), CheckConstraint("(is_prorated = 0 AND proration_numerator_days IS NULL AND proration_denominator_days IS NULL) OR (is_prorated = 1 AND proration_numerator_days IS NOT NULL AND proration_denominator_days IS NOT NULL AND typeof(proration_numerator_days) = 'integer' AND typeof(proration_denominator_days) = 'integer' AND proration_numerator_days > 0 AND proration_denominator_days > proration_numerator_days)"), CheckConstraint("(voided_at IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND void_reason IS NOT NULL AND length(trim(void_reason)) > 0)"), Index("rent_expectations_term_due", "lease_term_id", "due_on", unique=True), Index("rent_expectations_lease_due", "lease_id", "due_on"))

class RentExpectationTimelinessReviewModel(LocalBase):
    __tablename__ = "rent_expectation_timeliness_reviews"
    id: Mapped[str] = mapped_column(String, primary_key=True); expectation_id: Mapped[str] = mapped_column(ForeignKey("rent_expectations.id"), nullable=False); decision: Mapped[str] = mapped_column(String, nullable=False); reason: Mapped[str] = mapped_column(String, nullable=False); created_at: Mapped[str] = mapped_column(String, nullable=False)
    __table_args__ = (CheckConstraint("decision IN ('mark_missed', 'clear_missed')"), CheckConstraint("length(trim(reason)) > 0"), Index("rent_expectation_reviews_order", "expectation_id", "created_at", "id"))

class RentReceiptModel(LocalBase):
    __tablename__ = "rent_receipts"
    id: Mapped[str] = mapped_column(String, primary_key=True); lease_id: Mapped[str] = mapped_column(ForeignKey("leases.id"), nullable=False); idempotency_key: Mapped[str] = mapped_column(String, nullable=False, unique=True); received_on: Mapped[str] = mapped_column(String, nullable=False); amount_minor: Mapped[int] = mapped_column(Integer, nullable=False); currency_code: Mapped[str] = mapped_column(String, nullable=False); received_by_party_id: Mapped[str | None] = mapped_column(ForeignKey("parties.id")); replaces_receipt_id: Mapped[str | None] = mapped_column(ForeignKey("rent_receipts.id"), unique=True); notes: Mapped[str | None] = mapped_column(String); voided_at: Mapped[str | None] = mapped_column(String); void_reason: Mapped[str | None] = mapped_column(String); created_at: Mapped[str] = mapped_column(String, nullable=False)
    __table_args__ = (CheckConstraint("typeof(amount_minor) = 'integer' AND amount_minor > 0"), CheckConstraint("currency_code = 'USD'"), CheckConstraint("(voided_at IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND void_reason IS NOT NULL AND length(trim(void_reason)) > 0)"), Index("rent_receipts_lease_received", "lease_id", "received_on"))

class RentReceiptAllocationModel(LocalBase):
    __tablename__ = "rent_receipt_allocations"
    id: Mapped[str] = mapped_column(String, primary_key=True); receipt_id: Mapped[str] = mapped_column(ForeignKey("rent_receipts.id"), nullable=False); expectation_id: Mapped[str] = mapped_column(ForeignKey("rent_expectations.id"), nullable=False); amount_minor: Mapped[int] = mapped_column(Integer, nullable=False); created_at: Mapped[str] = mapped_column(String, nullable=False)
    __table_args__ = (CheckConstraint("typeof(amount_minor) = 'integer' AND amount_minor > 0"), Index("rent_receipt_allocations_one_receipt_expectation", "receipt_id", "expectation_id", unique=True), Index("rent_receipt_allocations_expectation", "expectation_id"))
