"""Application-owned contracts for INSP-001 persistence and evidence."""
from __future__ import annotations
from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol, TypeVar
from app.modules.files.domain.models import StoredFile
from app.modules.inspections.domain.models import ConditionAcknowledgment, ConditionArea, ConditionChecklistTemplate, ConditionChecklistTemplateItem, ConditionComparison, ConditionObservation, ConditionReport

Result = TypeVar("Result")

class InspectionTransaction(Protocol):
    def lease(self, item_id: str) -> Any: ...
    def termination_accepted(self, lease_id: str) -> bool: ...
    def report(self, item_id: str) -> ConditionReport | None: ...
    def reports(self, lease_id: str) -> list[ConditionReport]: ...
    def participants(self, lease_id: str) -> list[Any]: ...
    def areas(self, report_id: str) -> list[ConditionArea]: ...
    def observations(self, area_id: str) -> list[ConditionObservation]: ...
    def observation_context(self, observation_id: str) -> Any: ...
    def has_evidence(self, report_id: str) -> bool: ...
    def acknowledgments(self, report_id: str) -> list[ConditionAcknowledgment]: ...
    def comparisons(self, lease_id: str) -> list[ConditionComparison]: ...
    def template(self, item_id: str) -> ConditionChecklistTemplate | None: ...
    def template_items(self, template_id: str) -> list[ConditionChecklistTemplateItem]: ...
    def template_name_exists(self, normalized_name: str, excluding_id: str | None = None) -> bool: ...
    def insert_template(self, item: ConditionChecklistTemplate) -> None: ...
    def replace_template(self, item: ConditionChecklistTemplate) -> None: ...
    def insert_template_item(self, item: ConditionChecklistTemplateItem) -> None: ...
    def delete_template_items(self, template_id: str) -> None: ...
    def insert_report(self, item: ConditionReport) -> None: ...
    def replace_report(self, item: ConditionReport) -> None: ...
    def insert_area(self, item: ConditionArea) -> None: ...
    def insert_observation(self, item: ConditionObservation) -> None: ...
    def delete_report_children(self, report_id: str) -> None: ...
    def insert_acknowledgment(self, item: ConditionAcknowledgment) -> None: ...
    def delete_acknowledgment(self, item_id: str) -> None: ...
    def insert_comparison(self, item: ConditionComparison) -> None: ...
    def delete_comparison(self, item_id: str) -> None: ...
    def report_view(self, item_id: str) -> dict[str, object] | None: ...
    def file_transaction(self) -> Any: ...
    def record_change(self, **change: Any) -> None: ...

class InspectionUnitOfWork(Protocol):
    def write(self, operation: Callable[[InspectionTransaction], Result]) -> Result: ...
    def report_view(self, report_id: str) -> dict[str, object] | None: ...
    def report_views(self, lease_id: str) -> list[dict[str, object]]: ...
    def lease_summary(self, lease_id: str) -> dict[str, object] | None: ...
    def lease_exists(self, lease_id: str) -> bool: ...
    def template_views(self) -> list[dict[str, object]]: ...
    def template_view(self, template_id: str) -> dict[str, object] | None: ...

class InspectionEvidenceStore(Protocol):
    def add_in_transaction(self, transaction: Any, source: Path, original_name: str, media_type: str, *, entity_type: str, entity_id: str, purpose: str, correlation_id: str) -> tuple[StoredFile, Any]: ...
    def get(self, file_id: str) -> StoredFile: ...
