"""Application ports for provider workflows."""

from collections.abc import Callable, Collection, Mapping
from typing import Any, Protocol, TypeVar

from app.modules.parties.application.ports import PartyTransactionOperations
from app.modules.parties.domain.models import Party, PartyContactMethod
from app.modules.vendors.domain.models import (
    ProviderCategory,
    ProviderCategoryAssignment,
    ProviderProfile,
    ProviderReference,
    ProviderReputationLink,
    ProviderService,
    ProviderServiceArea,
    ProviderWorkHistory,
)

Result = TypeVar("Result")


class ProviderContextReader(Protocol):
    def profile_context(self, connection: Any, party_id: str) -> Mapping[str, object] | None: ...
    def profile_contexts(
        self, connection: Any, party_ids: Collection[str]
    ) -> Mapping[str, Mapping[str, object]]: ...
    def effective_categories(
        self, connection: Any, party_id: str
    ) -> list[Mapping[str, object]]: ...
    def effective_categories_for_providers(
        self, connection: Any, party_ids: Collection[str]
    ) -> Mapping[str, list[Mapping[str, object]]]: ...
    def active_category_catalog(self, connection: Any) -> list[Mapping[str, object]]: ...


class ProviderStorageConflict(RuntimeError):
    """Adapter-level unique or concurrent-write conflict."""


class PropertyAvailability(Protocol):
    def property(self, connection: Any, property_id: str) -> Any: ...


class ProviderTransaction(Protocol):
    def category_operation_by_key(self, key: str) -> Mapping[str, Any] | None: ...
    def insert_category_operation(self, operation: Mapping[str, Any]) -> None: ...
    def effective_assignment_counts(self, category_ids: Collection[str]) -> Mapping[str, int]: ...
    def operation_by_key(self, key: str) -> Mapping[str, Any] | None: ...
    def insert_operation(self, operation: Mapping[str, Any]) -> None: ...
    def party(self, party_id: str) -> Party | None: ...
    def methods(self, party_id: str) -> list[PartyContactMethod]: ...
    def insert_party(self, party: Party) -> None: ...
    def insert_method(self, method: PartyContactMethod) -> None: ...
    def duplicate_party_ids(self, methods: list[PartyContactMethod], limit: int) -> list[str]: ...
    def profile(self, party_id: str) -> ProviderProfile | None: ...
    def services(self, party_id: str) -> list[ProviderService]: ...
    def areas(self, party_id: str) -> list[ProviderServiceArea]: ...
    def work_history(self, party_id: str) -> list[ProviderWorkHistory]: ...
    def references(self, party_id: str) -> list[ProviderReference]: ...
    def reputation_links(self, party_id: str) -> list[ProviderReputationLink]: ...
    def category(self, category_id: str) -> ProviderCategory | None: ...
    def categories(
        self, archive_state: str, search: str | None = None
    ) -> list[ProviderCategory]: ...
    def assignments(
        self, party_id: str, *, include_archived: bool = True
    ) -> list[ProviderCategoryAssignment]: ...
    def assignment(self, assignment_id: str) -> ProviderCategoryAssignment | None: ...
    def insert_category(self, item: ProviderCategory) -> None: ...
    def replace_category(self, item: ProviderCategory) -> None: ...
    def insert_assignment(self, item: ProviderCategoryAssignment) -> None: ...
    def replace_assignment(self, item: ProviderCategoryAssignment) -> None: ...
    def property_exists(self, property_id: str) -> bool: ...
    def insert_profile(self, item: ProviderProfile) -> None: ...
    def replace_profile(self, item: ProviderProfile) -> None: ...
    def insert_service(self, item: ProviderService) -> None: ...
    def replace_service(self, item: ProviderService) -> None: ...
    def insert_area(self, item: ProviderServiceArea) -> None: ...
    def replace_area(self, item: ProviderServiceArea) -> None: ...
    def insert_work_history(self, item: ProviderWorkHistory) -> None: ...
    def replace_work_history(self, item: ProviderWorkHistory) -> None: ...
    def insert_reference(self, item: ProviderReference) -> None: ...
    def replace_reference(self, item: ProviderReference) -> None: ...
    def insert_reputation_link(self, item: ProviderReputationLink) -> None: ...
    def replace_reputation_link(self, item: ProviderReputationLink) -> None: ...
    def record_change(
        self,
        *,
        entity_type: str,
        entity_id: str,
        action: str,
        before: dict[str, Any] | None,
        after: dict[str, Any] | None,
        reason: str,
        correlation_id: str,
    ) -> None: ...


class ProviderUnitOfWork(Protocol):
    def category_operation(
        self, *, operation_id: str | None = None, key: str | None = None
    ) -> Mapping[str, Any] | None: ...
    def operation(
        self, *, operation_id: str | None = None, key: str | None = None
    ) -> Mapping[str, Any] | None: ...
    def write(self, operation: Callable[[ProviderTransaction], Result]) -> Result: ...
    def detail(
        self, party_id: str, *, include_archived: bool
    ) -> (
        tuple[
            Party,
            ProviderProfile,
            list[PartyContactMethod],
            list[ProviderService],
            list[ProviderServiceArea],
            list[ProviderWorkHistory],
            list[ProviderReference],
            list[ProviderReputationLink],
            list[tuple[ProviderCategoryAssignment, ProviderCategory]],
        ]
        | None
    ): ...
    def categories(
        self, archive_state: str, search: str | None = None
    ) -> list[ProviderCategory]: ...
    def effective_assignment_counts(self, category_ids: Collection[str]) -> Mapping[str, int]: ...
    def list(
        self,
        *,
        archive_state: str,
        search: str | None,
        service: str | None,
        service_area: str | None,
        selection_status: str | None,
        property_id: str | None,
        has_reference: bool | None,
        category_id: str | None = None,
        category_state: str | None = None,
        limit: int | None = None,
        cursor: tuple[str, str] | None = None,
    ) -> list[
        tuple[
            Party,
            ProviderProfile,
            list[ProviderService],
            list[ProviderServiceArea],
            int,
            int,
            int,
            list[tuple[ProviderCategoryAssignment, ProviderCategory]],
        ]
    ]: ...


class ProviderRoleActivityGuard(Protocol):
    def conflict(self, connection: Any, party_id: str) -> str | None: ...


def require_party_operations(value: PartyTransactionOperations) -> PartyTransactionOperations:
    """Keeps composition type errors close to the boundary."""
    return value
