"""Application ports for provider workflows."""

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.parties.application.ports import PartyTransactionOperations
from app.modules.parties.domain.models import Party, PartyContactMethod
from app.modules.vendors.domain.models import (
    ProviderProfile, ProviderReference, ProviderService, ProviderServiceArea, ProviderWorkHistory,
)

Result = TypeVar("Result")


class ProviderStorageConflict(RuntimeError):
    """Adapter-level unique or concurrent-write conflict."""


class PropertyAvailability(Protocol):
    def property(self, connection: Any, property_id: str) -> Any: ...


class ProviderTransaction(Protocol):
    def party(self, party_id: str) -> Party | None: ...
    def methods(self, party_id: str) -> list[PartyContactMethod]: ...
    def insert_party(self, party: Party) -> None: ...
    def insert_method(self, method: PartyContactMethod) -> None: ...
    def duplicate_party_ids(self, methods: list[PartyContactMethod], limit: int) -> list[str]: ...
    def profile(self, party_id: str) -> ProviderProfile | None: ...
    def services(self, party_id: str) -> list[ProviderService]: ...
    def areas(self, party_id: str) -> list[ProviderServiceArea]: ...
    def work_history(self, party_id: str) -> list[ProviderWorkHistory]: ...
    def references(self, party_id: str) -> list[ProviderReference]: ...
    def property_exists(self, property_id: str) -> bool: ...
    def insert_profile(self, item: ProviderProfile) -> None: ...
    def replace_profile(self, item: ProviderProfile) -> None: ...
    def insert_service(self, item: ProviderService) -> None: ...
    def replace_service(self, item: ProviderService) -> None: ...
    def insert_area(self, item: ProviderServiceArea) -> None: ...
    def replace_area(self, item: ProviderServiceArea) -> None: ...
    def insert_work_history(self, item: ProviderWorkHistory) -> None: ...
    def replace_work_history(self, item: ProviderWorkHistory) -> None: ...
    def insert_reference(self, item: ProviderReference) -> None: ...
    def replace_reference(self, item: ProviderReference) -> None: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str,
                      before: dict[str, Any] | None, after: dict[str, Any] | None,
                      reason: str, correlation_id: str) -> None: ...


class ProviderUnitOfWork(Protocol):
    def write(self, operation: Callable[[ProviderTransaction], Result]) -> Result: ...
    def detail(self, party_id: str, *, include_archived: bool) -> tuple[
        Party, ProviderProfile, list[PartyContactMethod], list[ProviderService],
        list[ProviderServiceArea], list[ProviderWorkHistory], list[ProviderReference],
    ] | None: ...
    def list(self, *, archive_state: str, search: str | None, service: str | None,
             service_area: str | None, selection_status: str | None,
             property_id: str | None, has_reference: bool | None) -> list[tuple[
                 Party, ProviderProfile, list[ProviderService], list[ProviderServiceArea],
                 int, int,
             ]]: ...


class ProviderRoleActivityGuard(Protocol):
    def conflict(self, connection: Any, party_id: str) -> str | None: ...


def require_party_operations(value: PartyTransactionOperations) -> PartyTransactionOperations:
    """Keeps composition type errors close to the boundary."""
    return value
