"""FIN-008 transaction boundary."""
from typing import Protocol


class DepositTransaction(Protocol):
    def lease_context(self, lease_id: str, lease_term_id: str): ...
    def party(self, party_id: str): ...
    def account(self, account_id: str): ...
    def account_for_lease(self, lease_id: str): ...
    def accounts(self, **filters): ...
    def receipt(self, receipt_id: str): ...
    def receipt_by_key(self, key: str): ...
    def receipt_replacement_exists(self, receipt_id: str): ...
    def receipt_replacement(self, receipt_id: str): ...
    def receipts(self, account_id: str, *, active_only: bool = False): ...
    def settlement(self, settlement_id: str): ...
    def settlements(self, account_id: str): ...
    def settlement_replacement_exists(self, settlement_id: str): ...
    def settlement_replacement(self, settlement_id: str): ...
    def settlement_receipt_ids(self, settlement_id: str): ...
    def capture_settlement_receipt(self, settlement_id: str, receipt_id: str, stamp: str): ...
    def deductions(self, settlement_id: str): ...
    def deduction(self, deduction_id: str): ...
    def credit(self, credit_id: str): ...
    def deduction_sources(self, deduction_id: str): ...
    def deduction_source(self, source_id: str): ...
    def insert_source(self, item: dict): ...
    def replace_source(self, item: dict): ...
    def source_context(self, source_kind: str, source_id: str): ...
    def expense_source_used_elsewhere(self, expense_id: str, deduction_id: str): ...
    def deduction_has_file_evidence(self, deduction_id: str): ...
    def evidence(self, entity_type: str, entity_id: str): ...
    def inspection_warnings(self, lease_id: str): ...
    def credits(self, settlement_id: str): ...
    def refunds(self, account_id: str, *, active_only: bool = False): ...
    def refund(self, refund_id: str): ...
    def refund_by_key(self, key: str): ...
    def refund_replacement_exists(self, refund_id: str): ...
    def refund_replacement(self, refund_id: str): ...
    def participants(self, lease_id: str): ...
    def insert(self, kind: str, item: dict): ...
    def replace(self, kind: str, item: dict): ...
    def delete(self, kind: str, record_id: str): ...
    def record_change(self, **kwargs): ...


class DepositUnitOfWork(Protocol):
    def read(self, operation): ...
    def write(self, operation): ...
