"""Transaction-aware ports for FIN-002 recorded expenses."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from app.modules.finance.domain.expense_models import Expense, ExpenseCategory, ExpenseRefund

Result = TypeVar("Result")


class PortfolioExpenseOperations(Protocol):
    def expense_context(self, connection: Any, property_id: str, space_id: str | None, paid_on: str) -> dict[str, object] | None: ...
    def party_owned_property_on(self, connection: Any, property_id: str, party_id: str, paid_on: str) -> bool: ...
    def expense_contexts(self, connection: Any, expenses: list[Expense]) -> dict[str, dict[str, object]]: ...


class ProviderExpenseOperations(Protocol):
    def expense_provider(self, connection: Any, party_id: str) -> dict[str, object] | None: ...
    def expense_providers(self, connection: Any, party_ids: list[str]) -> dict[str, dict[str, object]]: ...


class PartyExpenseOperations(Protocol):
    def exists(self, connection: Any, party_id: str) -> bool: ...
    def party_map(self, connection: Any, party_ids: list[str]) -> dict[str, Any]: ...


class FileExpenseOperations(Protocol):
    def evidence_for_expenses(self, connection: Any, expense_ids: list[str]) -> dict[str, list[dict[str, object]]]: ...
    def expense_ids_with_active_evidence(self, connection: Any) -> set[str]: ...


class ExpenseFileLinkOperations(Protocol):
    def expense_exists(self, connection: Any, expense_id: str) -> bool: ...
    def active_link_count(self, connection: Any, expense_id: str) -> int: ...


class ExpenseTransaction(Protocol):
    def category(self, category_id: str) -> ExpenseCategory | None: ...
    def categories(self, include_archived: bool) -> list[ExpenseCategory]: ...
    def category_by_name(self, normalized_name: str) -> ExpenseCategory | None: ...
    def insert_category(self, item: ExpenseCategory) -> None: ...
    def replace_category(self, item: ExpenseCategory) -> None: ...
    def expense(self, expense_id: str) -> Expense | None: ...
    def expense_by_key(self, idempotency_key: str) -> Expense | None: ...
    def expenses(self, **filters: object) -> list[Expense]: ...
    def duplicate_expenses(self, item: Expense) -> list[Expense]: ...
    def expense_projection(self, expenses: list[Expense]) -> dict[str, object]: ...
    def replacement_expense_exists(self, expense_id: str) -> bool: ...
    def insert_expense(self, item: Expense) -> None: ...
    def replace_expense(self, item: Expense) -> None: ...
    def refund(self, refund_id: str) -> ExpenseRefund | None: ...
    def refund_by_key(self, idempotency_key: str) -> ExpenseRefund | None: ...
    def refunds(self, expense_id: str) -> list[ExpenseRefund]: ...
    def replacement_refund_exists(self, refund_id: str) -> bool: ...
    def insert_refund(self, item: ExpenseRefund) -> None: ...
    def replace_refund(self, item: ExpenseRefund) -> None: ...
    def portfolio_context(self, property_id: str, space_id: str | None, paid_on: str) -> dict[str, object] | None: ...
    def provider_context(self, party_id: str) -> dict[str, object] | None: ...
    def party_exists(self, party_id: str) -> bool: ...
    def party_owned_property_on(self, property_id: str, party_id: str, paid_on: str) -> bool: ...
    def record_change(self, **change: Any) -> None: ...


class ExpenseUnitOfWork(Protocol):
    def write(self, operation: Callable[[ExpenseTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[ExpenseTransaction], Result]) -> Result: ...
