"""FIN-001 transaction boundaries."""
from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol, TypeVar
from app.modules.finance.domain.models import RentExpectation, RentReceipt

Result = TypeVar("Result")
@dataclass(frozen=True)
class LeaseTermFinanceSnapshot:
    id: str; lease_id: str; lease_status: str; property_id: str; space_id: str; time_zone: str; effective_on: str; ends_on: str | None; base_rent_minor: int; currency_code: str; payment_frequency: str; payment_due_day: int | None; actual_move_out_on: str | None; responsibility_ends_on: str | None
class LeaseFinanceOperations(Protocol):
    def term_snapshot(self, connection: Any, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshot(self, connection: Any, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshots(self, connection: Any, pairs: list[tuple[str, str]]) -> dict[tuple[str, str], LeaseTermFinanceSnapshot]: ...
    def lease_time_zone(self, connection: Any, lease_id: str) -> str | None: ...
class PartyFinanceOperations(Protocol):
    def exists(self, connection: Any, party_id: str) -> bool: ...
class FinanceTransaction(Protocol):
    def lease_term_snapshot(self, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshot(self, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshots(self, pairs: list[tuple[str, str]]) -> dict[tuple[str, str], LeaseTermFinanceSnapshot]: ...
    def party_exists(self, party_id: str) -> bool: ...
    def lease_time_zone(self, lease_id: str) -> str | None: ...
    def expectation(self, expectation_id: str) -> RentExpectation | None: ...
    def expectations_for_term(self, term_id: str) -> list[RentExpectation]: ...
    def expectations(self, **filters: Any) -> list[RentExpectation]: ...
    def expectation_page(self, *, lease_id: str | None, due_from: str | None, due_to: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentExpectation]: ...
    def receipt(self, receipt_id: str) -> RentReceipt | None: ...
    def receipt_page(self, *, lease_id: str | None, received_from: str | None, received_to: str | None, received_by_party_id: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentReceipt]: ...
    def receipt_chain_page(self, *, receipt_id: str, lease_id: str | None, received_from: str | None, received_to: str | None, received_by_party_id: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentReceipt]: ...
    def receipt_by_key(self, key: str) -> RentReceipt | None: ...
    def receipt_allocations(self, receipt_id: str) -> list[dict[str, Any]]: ...
    def receipt_projection(self, receipt_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def expectation_projection(self, expectation_ids: list[str]) -> dict[str, dict[str, Any]]: ...
    def allocated_amount(self, expectation_id: str) -> int: ...
    def receipt_activity_after(self, expectation_id: str, occurred_at: str) -> bool: ...
    def replacement_exists(self, receipt_id: str) -> bool: ...
    def reviews(self, expectation_id: str) -> list[dict[str, Any]]: ...
    def insert_expectation(self, item: RentExpectation) -> None: ...
    def replace_expectation(self, item: RentExpectation) -> None: ...
    def insert_receipt(self, item: RentReceipt) -> None: ...
    def replace_receipt(self, item: RentReceipt) -> None: ...
    def insert_allocation(self, item: dict[str, Any]) -> None: ...
    def insert_review(self, item: dict[str, Any]) -> None: ...
    def record_change(self, **change: Any) -> None: ...
class FinanceUnitOfWork(Protocol):
    def write(self, operation: Callable[[FinanceTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[FinanceTransaction], Result]) -> Result: ...
