"""FIN-001 transaction boundaries."""
from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol, TypeVar
from app.modules.finance.domain.models import PrepaidCheck, RentExpectation, RentReceipt

Result = TypeVar("Result")
@dataclass(frozen=True)
class LeaseTermFinanceSnapshot:
    id: str; lease_id: str; lease_status: str; property_id: str; space_id: str; time_zone: str; effective_on: str; ends_on: str | None; base_rent_minor: int; currency_code: str; payment_frequency: str; payment_due_day: int | None; actual_move_out_on: str | None; responsibility_ends_on: str | None
class PartyFinanceOperations(Protocol):
    def exists(self, connection: Any, party_id: str) -> bool: ...


class ExpenseContextReader(Protocol):
    """Minimal FIN-002 facts that another aggregate may read transactionally."""

    def expense_context(self, connection: Any, expense_id: str) -> dict[str, object] | None: ...
    def expense_contexts(self, connection: Any, expense_ids: list[str]) -> dict[str, dict[str, object]]: ...
class ReceiptTransactionOperations(Protocol):
    """Neutral FIN-001 operations on a caller-owned transaction."""
    def transaction(self, connection: Any): ...
    def record_receipt(self, connection: Any, command: Any, *, now: Callable[[], Any], correlation_id: str, audit_reason: str, duplicate_conflict: Callable[[list[RentReceipt]], Exception] | None = None) -> "RecordedReceipt": ...
    def receipt_contexts(self, connection: Any, receipt_ids: list[str]) -> dict[str, RentReceipt]: ...
    def receipt_lifecycle_predicate(self, lifecycle: str, receipt_id: Any) -> Any: ...
    def replacement_receipt(self, connection: Any, receipt_id: str) -> RentReceipt | None: ...


@dataclass(frozen=True)
class RecordedReceipt:
    """Result of a caller-owned FIN-001 record attempt.

    `created` lets a composing workflow preserve an explicit "create" choice
    instead of accidentally adopting a FIN idempotency retry.
    """
    receipt: RentReceipt
    created: bool
class FinanceTransaction(Protocol):
    def lease_term_snapshot(self, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshot(self, lease_id: str, term_id: str) -> LeaseTermFinanceSnapshot | None: ...
    def historical_term_snapshots(self, pairs: list[tuple[str, str]]) -> dict[tuple[str, str], LeaseTermFinanceSnapshot]: ...
    def party_exists(self, party_id: str) -> bool: ...
    def lease_time_zone(self, lease_id: str) -> str | None: ...
    def participant_active(self, lease_id: str, party_id: str, on: str) -> bool: ...
    def expectation(self, expectation_id: str) -> RentExpectation | None: ...
    def expectations_for_term(self, term_id: str) -> list[RentExpectation]: ...
    def expectations(self, **filters: Any) -> list[RentExpectation]: ...
    def expectation_page(self, *, lease_id: str | None, due_from: str | None, due_to: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentExpectation]: ...
    def receipt(self, receipt_id: str) -> RentReceipt | None: ...
    def latest_non_voided_receipt(self, lease_id: str) -> RentReceipt | None: ...
    def likely_duplicate_receipts(self, *, lease_id: str, received_on: str, amount_minor: int, received_by_party_id: str | None, limit: int = 20) -> list[RentReceipt]: ...
    def receipt_page(self, *, lease_id: str | None, received_from: str | None, received_to: str | None, received_by_party_id: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentReceipt]: ...
    def receipt_chain_page(self, *, receipt_id: str, lease_id: str | None, received_from: str | None, received_to: str | None, received_by_party_id: str | None, include_voided: bool, cursor: tuple[str, str] | None, limit: int) -> list[RentReceipt]: ...
    def receipt_by_key(self, key: str) -> RentReceipt | None: ...
    def receipt_allocations(self, receipt_id: str) -> list[dict[str, Any]]: ...
    def receipt_projection(self, receipt_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def expectation_projection(self, expectation_ids: list[str]) -> dict[str, dict[str, Any]]: ...
    def allocated_amount(self, expectation_id: str) -> int: ...
    def receipt_activity_after(self, expectation_id: str, occurred_at: str) -> bool: ...
    def replacement_exists(self, receipt_id: str) -> bool: ...
    def reviews(self, expectation_id: str) -> list[dict[str, Any]]: ...
    def insert_expectation(self, item: RentExpectation) -> None: ...
    def replace_expectation(self, item: RentExpectation) -> None: ...
    def insert_receipt(self, item: RentReceipt) -> None: ...
    def replace_receipt(self, item: RentReceipt) -> None: ...
    def insert_allocation(self, item: dict[str, Any]) -> None: ...
    def insert_review(self, item: dict[str, Any]) -> None: ...
    def prepaid_check(self, check_id: str) -> PrepaidCheck | None: ...
    def prepaid_checks(self, *, lease_id: str | None = None, status: str | None = None) -> list[PrepaidCheck]: ...
    def prepaid_check_page(self, *, lease_id: str | None, payer_party_id: str | None, expectation_id: str | None, status: str | None, cursor: tuple[str, str] | None, limit: int) -> list[PrepaidCheck]: ...
    def prepaid_check_by_operation_key(self, key: str) -> dict[str, Any] | None: ...
    def prepaid_check_by_receipt(self, receipt_id: str) -> PrepaidCheck | None: ...
    def insert_prepaid_check(self, item: PrepaidCheck) -> None: ...
    def replace_prepaid_check(self, item: PrepaidCheck) -> None: ...
    def insert_prepaid_check_operation(self, item: dict[str, Any]) -> None: ...
    def create_prepaid_check_reminder(self, *, check_id: str, due_at_utc: str, due_timezone: str, correlation_id: str) -> str: ...
    def dismiss_prepaid_check_reminder(self, task_id: str | None, *, correlation_id: str) -> None: ...
    def prepaid_check_reminder_status(self, task_id: str | None) -> str | None: ...
    def record_change(self, **change: Any) -> None: ...
class FinanceUnitOfWork(Protocol):
    def write(self, operation: Callable[[FinanceTransaction], Result]) -> Result: ...
    def read(self, operation: Callable[[FinanceTransaction], Result]) -> Result: ...
