"""Transaction ports for tenant contact changes."""
from collections.abc import Callable
from typing import Any, Protocol, TypeVar
from app.modules.parties.domain.models import Party
from app.modules.tenants.domain.models import TenantContactMethod, TenantProfile

Result = TypeVar("Result")

class TenantTransaction(Protocol):
    def party(self, party_id: str) -> Party | None: ...
    def profile(self, party_id: str) -> TenantProfile | None: ...
    def methods(self, party_id: str) -> list[TenantContactMethod]: ...
    def has_open_lease_participation(self, party_id: str, today: str) -> bool: ...
    def insert_party(self, party: Party) -> None: ...
    def insert_profile(self, profile: TenantProfile) -> None: ...
    def replace_profile(self, profile: TenantProfile) -> None: ...
    def insert_method(self, method: TenantContactMethod) -> None: ...
    def replace_method(self, method: TenantContactMethod) -> None: ...
    def record_change(self, *, entity_type: str, entity_id: str, action: str, before: dict[str, Any] | None, after: dict[str, Any] | None, reason: str, correlation_id: str) -> None: ...

class TenantUnitOfWork(Protocol):
    def write(self, operation: Callable[[TenantTransaction], Result]) -> Result: ...
    def get(self, party_id: str) -> tuple[Party, TenantProfile, list[TenantContactMethod]] | None: ...
    def list(self, *, archive_state: str, search: str | None) -> list[tuple[Party, TenantProfile, list[TenantContactMethod]]]: ...
