"""Provider, credential, and review extension contracts owned by AI governance."""
from __future__ import annotations
from dataclasses import dataclass
from collections.abc import Callable
from typing import Any, Mapping, Protocol, TypeVar


@dataclass(frozen=True)
class AiProviderResult:
    payload: Mapping[str, Any]
    confidence: Mapping[str, Any] | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    provider_request_id: str | None = None


class AiProviderError(RuntimeError):
    code = "ai_provider_failure"


class AiProviderPort(Protocol):
    def estimate_input_tokens(self, provider_request: Mapping[str, Any], model_identifier: str) -> int: ...
    def probe(self, provider_request: Mapping[str, Any], model_identifier: str,
              timeout_seconds: int) -> AiProviderResult: ...
    def generate(self, provider_request: Mapping[str, Any], model_identifier: str, max_completion_tokens: int, timeout_seconds: int) -> AiProviderResult: ...


class AiTransportCredentialStore(Protocol):
    def get_credential(self, workspace_id: str, connection_id: str) -> str | None: ...
    def set_credential(self, workspace_id: str, connection_id: str, credential: str) -> None: ...
    def delete_credential(self, workspace_id: str, connection_id: str) -> None: ...


@dataclass(frozen=True)
class AiApprovalContext:
    """Immutable facts an owner needs to reject a stale proposal."""
    draft_id: str
    draft_version: int
    action_type: str
    draft_payload: Mapping[str, Any]
    source_entity_type: str
    source_entity_id: str
    source_revision: str
    source_fingerprint: str
    correlation_id: str
    operator_note: str | None


class AiApprovalHandler(Protocol):
    """Owning domain opens its own transaction and completes review there."""
    def approve(self, context: AiApprovalContext) -> Mapping[str, Any]: ...


class AiApprovalEvidenceValidator(Protocol):
    """Owning-domain retained-history check used during workspace validation."""
    def validate_approval_evidence(self, connection: Any, *,
                                   action_type: str,
                                   decision: Mapping[str, Any],
                                   run: Mapping[str, Any]) -> None: ...


class AiSourceValidator(Protocol):
    """Source-owner checks for a live command and for retained history.

    A live reservation must match the current source exactly.  Restore is
    intentionally different: an old revision is valid evidence when the
    source still exists, or when its owner retained an explicit tombstone.
    """
    def validate_current_source(self, connection: Any, *, source_entity_type: str,
                                source_entity_id: str, source_revision: str,
                                source_fingerprint: str) -> None: ...
    def validate_retained_source(self, connection: Any, *, source_entity_type: str,
                                 source_entity_id: str, source_revision: str,
                                 source_fingerprint: str) -> None: ...


class AiSourceProjection(Protocol):
    """Owning-domain runtime projection; may return an explicit tombstone."""
    def source_state(self, *, source_entity_type: str, source_entity_id: str) -> Mapping[str, Any] | None: ...


class AiReviewOperations(Protocol):
    """Transaction operations supplied to an owning-domain approval handler."""
    def draft(self, draft_id: str) -> Mapping[str, Any] | None: ...
    def complete_approval(self, *, draft_id: str, expected_version: int,
                          result_entity_type: str | None, result_entity_id: str | None,
                          operator_note: str | None) -> Mapping[str, Any]: ...


Result = TypeVar("Result")


class AiGovernanceTransactionOperations(Protocol):
    """Persistence operations used by AI application services in one write transaction."""
    def settings(self) -> Mapping[str, Any]: ...
    def update_settings(self, values: Mapping[str, Any]) -> None: ...
    def settings_operation(self, idempotency_key: str) -> Mapping[str, Any] | None: ...
    def insert_settings_operation(self, values: Mapping[str, Any]) -> None: ...
    def model_connection(self, connection_id: str) -> Mapping[str, Any] | None: ...
    def connections(self) -> list[Mapping[str, Any]]: ...
    def insert_connection(self, values: Mapping[str, Any]) -> None: ...
    def replace_connection(self, connection_id: str, values: Mapping[str, Any]) -> None: ...
    def action_limit(self, action_type: str) -> Mapping[str, Any] | None: ...
    def action_limits(self) -> list[Mapping[str, Any]]: ...
    def put_action_limit(self, values: Mapping[str, Any]) -> None: ...
    def run_by_key(self, key: str) -> Mapping[str, Any] | None: ...
    def validate_current_source(self, *, source_entity_type: str, source_entity_id: str,
                                source_revision: str, source_fingerprint: str) -> None: ...
    def run(self, run_id: str) -> Mapping[str, Any] | None: ...
    def insert_run(self, values: Mapping[str, Any]) -> None: ...
    def update_run(self, run_id: str, values: Mapping[str, Any]) -> None: ...
    def active_run_count(self, action_type: str, day_start: str, day_end: str) -> int: ...
    def draft(self, draft_id: str) -> Mapping[str, Any] | None: ...
    def draft_for_run(self, run_id: str) -> Mapping[str, Any] | None: ...
    def insert_draft(self, values: Mapping[str, Any]) -> None: ...
    def update_draft(self, draft_id: str, values: Mapping[str, Any]) -> None: ...
    def insert_decision(self, values: Mapping[str, Any]) -> None: ...
    def interrupted_runs(self) -> list[Mapping[str, Any]]: ...
    def record_audit(self, *, entity_type: str, entity_id: str, action: str,
                     before: Mapping[str, Any] | None, after: Mapping[str, Any] | None,
                     correlation_id: str, actor: str, reason: str) -> None: ...


class AiGovernanceUnitOfWork(Protocol):
    """Application boundary; concrete SQLite transactions stay infrastructure-owned."""
    def write(self, operation: Callable[[AiGovernanceTransactionOperations], Result]) -> Result: ...
    def settings_row(self) -> Mapping[str, Any]: ...
    def connection_row(self, connection_id: str) -> Mapping[str, Any] | None: ...
    def connection_rows(self) -> list[Mapping[str, Any]]: ...
    def action_limit_row(self, action_type: str) -> Mapping[str, Any] | None: ...
    def action_limit_rows(self) -> list[Mapping[str, Any]]: ...
    def run_row(self, run_id: str) -> Mapping[str, Any] | None: ...
    def page_draft_rows(self, *, status: str | None, owning_module: str | None,
                        entity_kind: str | None, action_type: str | None,
                        source_type: str | None, source_id: str | None,
                        limit: int, cursor: tuple[str, str] | None) -> list[Mapping[str, Any]]: ...
    def draft_detail_row(self, draft_id: str) -> Mapping[str, Any] | None: ...
    def draft_decision_rows(self, draft_id: str) -> list[Mapping[str, Any]]: ...
    def approval_context_row(self, draft_id: str) -> Mapping[str, Any] | None: ...
